language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  npm: true
script:
  - npm i -g widdershins
  - widdershins ./openapi.yaml -o output.md
  - 'git config --global user.name "${GH_NAME}"'
  - 'git config --global user.email "${GH_EMAIL}"'
  - 'echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc'
  - 'git clone https://github.com/apidocsfordevs/pantheon-docs.git'
  - cd pantheon-docs
  - cp ../output.md ./docs/conversations.md
  - git add ./docs/conversations.md
  - git commit -m "Built docs via Travis CI" --allow-empty
  - git push
before_install:
  - npm install dredd@13.1.2 --global
before_script:
  - dredd
